package org.entur.ror.ubelluris.model

object NetexTypes {
    const val SITE_FRAME = "SiteFrame"
    const val CODESPACE = "Codespace"
    const val XML_NS = "Xmlns"
    const val XML_NS_URL = "XmlnsUrl"
    const val STOP_PLACE = "StopPlace"
    const val STOP_PLACE_TYPE = "StopPlaceType"
    const val PARENT_SITE_REF = "ParentSiteRef"
    const val SCHEDULED_STOP_POINT_REF = "ScheduledStopPointRef"
    const val ROUTE = "Route"
    const val ROUTE_REF = "RouteRef"
    const val STOP_POINT_IN_JOURNEY_PATTERN = "StopPointInJourneyPattern"
    const val JOURNEY_PATTERN = "JourneyPattern"
    const val QUAY = "Quay"
    const val PUBLIC_CODE = "PublicCode"
    const val KEY_VALUE = "KeyValue"
    const val KEY = "Key"
    const val VALUE = "Value"
    const val LINE = "Line"
    const val LINE_REF = "LineRef"
    const val TRANSPORT_MODE = "TransportMode"
    const val SERVICE_JOURNEY_INTERCHANGE = "ServiceJourneyInterchange"
    const val SERVICE_JOURNEY = "ServiceJourney"
    const val OPERATOR = "Operator"
    const val OPERATOR_REF = "OperatorRef"
}
