name: Build and push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gradle-build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21.0.5+11
          distribution: liberica
          cache: gradle
      - name: Lint with ktlint
        run: ./gradlew ktlintCheck
      - name: Run gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v4.6.2
        with:
          path: build/libs/*.jar
          name: artifact
  docker-lint:
    needs: [gradle-build]
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      ignore: DL3018
  docker-build:
    if: github.repository_owner == 'entur' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [gradle-build]
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: artifact
      build_artifact_path: build/libs
  docker-push:
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1
  docker-scan:
    needs: [ docker-build ]
    uses: entur/gha-security/.github/workflows/docker-scan.yml@v2
    with:
      image_artifact: ${{ needs.docker-build.outputs.image_artifact }}
